Update patch set 3
Patch Set 3:

> Patch Set 3:
> 
> Why was this reverted the first time?

It caused telemetry_perf_unittests to fail to deserialize a histogram set json that contained TagMap.
process_perf_results_unittest.ProcessPerfResultsIntegrationTest.testIntegration
Error: Unable to find shared Diagnostic fae827d9-4ef9-4a10-bd75-bb4f9a8cd8e0
    at Map.resolveSharedDiagnostics (/tracing/value/diagnostics/diagnostic_map.html:99:17)
    at HistogramSet.importDict (/tracing/value/histogram_set.html:182:26)
    at HistogramSet.importDicts (/tracing/value/histogram_set.html:160:14)
    at mergeHistograms (/usr/local/google/home/benjhayden/dev/cr/b/src/third_party/catapult/tracing/tracing/value/merge_histograms_cmdline.html:69:14)

In order to maintain backwards compatibility while removing support for TagMap, I tried to make it ignore TagMaps when deserializing. I based this ignoring on the way that I did it for RelatedHistograms, but I forgot that TagMaps are shared diagnostics, which are serialized differently from non-shared Diagnostics like RelatedHistograms. HistogramSet JSON v2019 will fix this problem by serializing all diagnostics the same way.

Patchset 3 fixes ignoring TagMaps when deserializing by making DiagnosticMap.addDicts ignore all diagnostics and DiagnosticRefs named 'tagmap'. Since 'tagmap' has been a reserved name, nobody is using it. In a few weeks, we should be able to remove the hack for both 'tagmap' and RelatedHistograms.

Patch-set: 3
Reviewer: Gerrit User 1115874 <1115874@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>