Update Flask and Werkzeug version
Current catapult cloud build uses Flask version 2.0.1 and Werkzeug version 2.1.0 which resulted "TypeError: __init__() got an unexpected keyword argument 'as_tuple'" in the cloud build process, see link(https://pantheon.corp.google.com/cloud-build/builds/6402df4a-8b9e-48c8-9137-bf373f5b70a6;step=3?project=chromeperf). Update Flask version to 2.1.0 and set Werkzeug version to 2.1.0 to avoid version conflicts.

Bug: chromium:1311445
Change-Id: Ie310cab97ec9f45ff9fc87f6ba4713ba9a3a485e