Update patch set 1
Patch Set 1:

Based on the docstring of FindBrowser():
  Returns:
    A PossibleBrowser object.
  Raises:
    BrowserFinderException: Options improperly set, or an error occurred.

Caller should receive a PossibleBrowser object or exception. But if there're more than a few caller handling None instead of catching exception, then we should at least fix the docstring.

Though I prefer treating "cannot find any browser" as an exception because it is definitely something wrong for the platform.

Patch-set: 1
Reviewer: Gerrit User 1001853 <1001853@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>