Update patch set 6
Patch Set 6:

Looks good overall, though I'm not a fan with having a `FromProto` to every diagnostic type -- but I guess that's what we need to do anyway?

BTW, the error is at:

```
Failed to import test module: add_histograms_queue_test
Traceback (most recent call last):
  File "/b/s/w/ir/cipd_bin_packages/cpython/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/b/s/w/ir/cipd_bin_packages/cpython/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/b/s/w/ir/k/catapult/dashboard/dashboard/add_histograms_queue_test.py", line 17, in <module>
    from dashboard import add_histograms_queue
  File "/b/s/w/ir/k/catapult/dashboard/dashboard/add_histograms_queue.py", line 28, in <module>
    from tracing.value import histogram as histogram_module
  File "/b/s/w/ir/k/catapult/tracing/tracing/value/histogram.py", line 21, in <module>
    from tracing import histogram_pb2
ImportError: cannot import name histogram_pb2
```

You probably need to ensure that the histogram proto is built in the Dashboard tests from  `catapult_build/build_steps.py`.

https://source.chromium.org/chromium/_/chromium/catapult.git/+/09b742896513eb94aa3cd506f7c4bc5dcce84f95:catapult_build/build_steps.py;l=247-271;drc=13cb57d5162ade2775ae1bcf8ba0f06cf6f31332?originalUrl=https:%2F%2Fcs.chromium.org%2F

Patch-set: 6
Reviewer: Gerrit User 1327821 <1327821@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>