Update patch set 4
Patch Set 4:

> Patch Set 4:
> 
> This is great Dave, I love this!
> 
> Some high level comments on the UI:
> 
> * The matrix with test results shows for me some disabled scrollbars [1], is that intended? I guess we should never show vertical scrollbar, and only show the horizontal one if there are lots of repeats?
> * I found it confusing to understand what happens when you click on a dot on the graph. I saw the commit's changing, but wan't sure exactly just how. After a while I realized that clicking on a dot selects that commit to appear on the right side panel, and the one on the left side  is always the immediately preceding commit. I think that's fine, but the confusion could be solved if:
>   - somehow, there was some visual feedback on the dots when selecting them; i.e. highlight the two ones that are being shown below.
>   - when clicking on the first dot; instead of just showing that commit on the right and nothing on the left, just show me a comparison between the first two commits?
> * Somewhat unrelated to this change, but it would be great if the histogram to the right of the graph was also comparing the distributions of the two selected commits?
> 
> [1]: https://screenshot.googleplex.com/jYCKYXK9GGS.png

Also another (maybe not terribly related) comment: when things fail and we show an exception stack trace, this is often the stack trace from pinpoint, e.g.:

Traceback (most recent call last):
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-b76f0192.411387778728304510/dashboard/pinpoint/models/quest/execution.py", line 95, in Poll
    self._Poll()
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-b76f0192.411387778728304510/dashboard/pinpoint/models/quest/run_test.py", line 211, in _Poll
    'message was:\n%s' % exception_string)
SwarmingTestError: The test failed. The test's error message was:
TimeoutException: Timed out while waiting 180s for HasReachedQuiescence.

Which might be useful pinpoint debugging but not so much for the users who just want to know what went wrong with the test. Could we either (a) pull back the full error trace from the test [I know that's hard] or (b) maybe just show the last bit which is the relevant part, e.g.:

  The test failed. The test's error message was:
  TimeoutException: Timed out while waiting 180s for HasReachedQuiescence.

Patch-set: 4