Update patch set 12
Patch Set 12:

> Patch Set 12:
> 
> > Patch Set 6:
> > 
> > > Patch Set 6:
> > > 
> > > Did some testing in dev_console with queries that have no composite index, like querying on description/overridden_anomaly_config and seems to work fine. Had some slight concerns there might be some weirdness surrounding the computed properties, but poking through the source reveals that they're indexed by default although there isn't much mention in the docs.
> > > 
> > > Any idea if the non-composite index backed query performs similarly? This will definitely impact people since list_tests is used by the test-picker.
> > 
> > I changed the CL to keep the index for the deprecated,description projection query because it seems to make all the difference in performance for update_test_suites.
> > 
> 
> I'm betting this is because of the monitored property, which has actually been removed but most class instances will still have one. If we resaved old TestMetadata's without that property, this projection query may not be needed.
> 
> > I believe list_tests is already using the builtin indexes instead of the composite indexes. The composite indexes would only support queries that specify all of master_name,bot_name,suite_name,test_part1_name,test_part2_name,test_part3_name,test_part4_name,test_part5_name. If a query specifies all parts of the test path, uniquely identifying a single TestMetadata entity, then why run the query in the first place?
> > 
> 
> https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/list_tests.py#L256
> 
> Believe TestMetadata writes out '' to any unused portion of the path, and the entire query is specified every time when using list_tests.

It only filters test_partN_name=='' for the parts after the specified pattern.
Consider a request pattern like 'Master/Bot/Suite/Measurement/*'. len(pattern_parts) = 5. property_names[5] = 'test_part3_name'. This request will query(master=='Master',bot=='Bot',suite=='Suite',part1=='Measurement',part3=='',part4=='',part5==''). It won't specify the property corresponding to the '*', test_part2_name, because the caller wants to list the options for that part, so it won't hit the index. If there were an index that omitted test_part2_name, then that pattern would hit that index.

> 
> > > 
> > > This isn't super high priority though, so maybe let's try this once all the alerts indexes stuff has landed. Also for the Test entity, should we also be removing these from datastore? Anybody know?
> > 
> > The Test Model has been removed, so you can't even get a Test entity by key.
> > from google.appengine.ext import ndb
> > print ndb.Key('Master', 'ChromeOSPerf', 'Bot', 'cros-butterfly', 'Test', 'build_RootFilesystemSize', 'Test', 'bytes_rootfs_prod').get()
> > KindError: No model class found for kind 'Test'. Did you forget to import it?
> > 
> > Row still uses Test Keys for its parent_test computed property, which is used to define all its composite indexes. However, it doesn't appear to be necessary for the Test entities to exist for these Test Keys. I created a Row entity whose parent is ndb.Key('TestMetadata','ChromeOSPerfFyi/histogram-diff-chartjson-13/system_health.common_desktop/benchmark_duration/foo'). I can find it in the datastore by filtering for parent_test=Key(Master, 'ChromeOSPerfFyi', Bot, 'histogram-diff-chartjson-13', Test, 'system_health.common_desktop', Test, 'benchmark_duration', Test, 'foo') even though no such Test entity exists.
> > 
> > It looks to me like it would be safe to delete all of the Test entities.
> 
> Would like to hear from Annie here, but deleting them sounds good. I'd kinda want to remove all uses of them from the code first, if possible. Let's pick up the discussion once Annie is back.

Patch-set: 12
Reviewer: Gerrit User 1115874 <1115874@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>