Update patch set 4
Patch Set 4:

> Patch Set 4:
> 
> +Ben
> 
> For some backgrounds, I am trying to test-run cluster-telemetry with this CL - PageLoadAnalysis's LoadingMetric. 
> 
> Yet I am getting errors about "stableID":
> ```
>   Add at /b/storage/chromium/src/third_party/catapult/tracing/tracing/value/histogram.py:601
>     self._events_by_stable_id[event['stableId']] = event
> KeyError: 'stableId'
> ```
> (https://chrome-swarming.appspot.com/task?id=3d7843d840dedc10&refresh=10&show_raw=1)
> 
> While running it with normal loadingMetric there is no such issue. I am guessing it might have to do with the hacks I used to collect traces, but I am not sure.
> https://chromium-review.googlesource.com/c/catapult/+/833151/3/telemetry/telemetry/internal/results/page_test_results.py#255
> 
> Do you have any suggestions as for where to look at? Thanks!

Sorry, I just saw this question.

The KeyError suggests that a metric is creating a RelatedEventSet for an event that doesn't have a stableId. If you can save a trace that causes this error, then you can try to figure out what kind of event doesn't have stableId and catch it in tr.v.d.RelatedEventSet.asDictInto_ with something like this:
      for (const event of this) {
        if (!event.stableId) {
          console.error('Event sans stableId', event);
          continue;
        }

Does that help?

Patch-set: 4
Reviewer: Gerrit User 1115874 <1115874@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>