Revert "[Telemetry] Remove PageTestResults.failures getter"
This reverts commit f050e0106ffa961c966437596ac0a0ecaabff6ec.

Reason for revert: Still blocking catapult roller

benchmarks.blink_perf_unittest.BlinkPerfTest.testBlinkPerfTracingMetricsForMeasureAsync

Fails with:

    File "/b/swarming/w/ir/tools/perf/benchmarks/blink_perf_unittest.py", line 115, in testBlinkPerfTracingMetricsForMeasureAsync
      self.assertFalse(results.failures)
  AttributeError: 'PageTestResults' object has no attribute 'failures'

See: https://chromium-review.googlesource.com/c/chromium/src/+/942051

Original change's description:
> [Telemetry] Remove PageTestResults.failures getter
> 
> After crrev.com/c/940267 lands, there will be no remaining users of the
> PageTestResults.failures getter.
> 
> Bug: catapult:#4229
> Change-Id: I0cd2df650caca394fcb3717c8614123f3cbae9b1
> Reviewed-on: https://chromium-review.googlesource.com/940268
> Reviewed-by: Ned Nguyen <nednguyen@google.com>
> Commit-Queue: Ethan Kuefner <eakuefner@chromium.org>

TBR=eakuefner@chromium.org,nednguyen@google.com

Change-Id: I8722d6b7e811ad95afefdb09c8cb8145a6f3f9b2
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: catapult:#4229