Add .vpython file for histogram_proto.py.
Starting from [1], //third_party/protobuf has been updated to 3.13.0
and this introduces a breaking change which breaks WebRTC's perf results
upload (see bugs.webrtc.org/12211).

Error:

File [..]/tracing/proto/histogram_proto.py", line 9, in <module>
    import histogram_pb2  # pylint:disable=relative-import
  File "[..]/tracing/proto/histogram_pb2.py", line 22, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: 'module' object has no attribute '_internal_create_key'

[1] - https://chromium-review.googlesource.com/c/chromium/src/+/2545204

(See bugs.webrtc.org/12211)

Bug: None

Change-Id: I43d624fe29948c72421a5da55f4ffcd8e2dac942