[chromeperf] further fixes on the byte conversion on upload-processing
The previous fix did not fully fix the issue: https://chromium-review.googlesource.com/c/catapult/+/4070864. The following error happened:

File "/layers/google.python.pip/pip/lib/python3.9/site-packages/ijson/compat.py", line 32, in read
    return self.str_reader.read(n).encode('utf-8')
AttributeError: 'bytes' object has no attribute 'encode'

The suspected culprit is the DecompressFileWrapper which returns unicode string (I don't know why) when the buffer to read is empty. That will confuse ijson that the data is string instead of byte, and thus ijson will further encode it.


Bug: chromium:1298177
Change-Id: I6d7c8c5c985e944343ce20471a69123f1c44cda7