Update patch set 7
Patch Set 7:

Juan, ptal at the latest patch set.
This restores the 6 wait on desktop after flushing the system cache. This fixes GPU memory issue.

Pinpoints:
https://pinpoint-dot-chromeperf.appspot.com/job/16c87d74c40000
https://pinpoint-dot-chromeperf.appspot.com/job/16f2e06cc40000

The number of runs differ because some jobs fail with:

Traceback (most recent call last):
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-72f48c25.408843220466433796/dashboard/pinpoint/models/quest/execution.py", line 99, in Poll
    self._Poll()
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-72f48c25.408843220466433796/dashboard/pinpoint/models/quest/run_test.py", line 196, in _Poll
    raise SwarmingTestError(self._task_id, result['exit_code'])
SwarmingTestError: The swarming task 3cc4de3c5e8c0610 failed. The test exited with code 1.

Patch-set: 7
Reviewer: Gerrit User 1002405 <1002405@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>