Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> Do you mind pointing out what went wrong with the first landing and what's changed

Sorry, here's the exception from the initial CL that was blocking roll:
Traceback (most recent call last):
  File "/b/swarming/w/ir/third_party/catapult/tracing/bin/add_reserved_diagnostics", line 112, in <module>
    sys.exit(main())
  File "/b/swarming/w/ir/third_party/catapult/tracing/bin/add_reserved_diagnostics", line 102, in main
    f.write(json_batches)
TypeError: expected a string or other character buffer object

Patchset 2 contains the fix, which is to change that line to
f.write(json_batches[0])

Patch-set: 2
Reviewer: Gerrit User 1115874 <1115874@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>