Revert "[typ] Work around Mac file name limit"
This reverts commit 89bfb0515c819b2b18f23d427fd18d466b186db0.

Reason for revert: 
Catapult autoroll is failing:
https://chromium-review.googlesource.com/c/chromium/src/+/3687941/
https://ci.chromium.org/ui/p/chromium/builders/try/mac-rel/1017835/overview

Traceback (most recent call last):
  File "/opt/s/w/ir/third_party/blink/tools/blinkpy/web_tests/controllers/test_result_sink_unittest.py", line 252, in test_device_failure
    tr = test_results.TestResult(test_name='test-name')
  File "/opt/s/w/ir/third_party/blink/tools/blinkpy/web_tests/models/test_results.py", line 132, in __init__
    self.artifacts = Artifacts(
  File "/opt/s/w/ir/third_party/catapult/third_party/typ/typ/artifacts.py", line 94, in __init__
    if host.platform == 'win32':
AttributeError: 'NoneType' object has no attribute 'platform'

Original change's description:
> [typ] Work around Mac file name limit
>
> Adds a workaround to the artifacts implementation for Mac's 255
> character for any one piece of a filepath. If a part of the path is
> detected as being over the limit (likely a long test name), it gets
> replaced with a SHA1 hash.
>
> Also adds a few unittests for a similar Windows workaround that were
> missing.
>
> Bug: dawn:1446
> Change-Id: I502ef1c6d879f12c1f1618aaaac294bf5105af90
> Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/3685249
> Commit-Queue: Rakib Hasan <rmhasan@google.com>
> Reviewed-by: Rakib Hasan <rmhasan@google.com>
> Auto-Submit: Brian Sheedy <bsheedy@chromium.org>

Bug: dawn:1446
Change-Id: Ib3337801dfc40fb8c882446a81ba1ffcc0d678c2
No-Presubmit: true
No-Tree-Checks: true
No-Try: true