[chromeperf] check if bug is is none before comparing
Fixing the following issue in Python3:

 File "/workspace/dashboard/alerts.py", line 183, in AnomalyDicts
    bisect_statuses = _GetBisectStatusDict(anomalies)
  File "/workspace/dashboard/alerts.py", line 268, in _GetBisectStatusDict
    bug_id_list = {a.bug_id for a in anomalies if a.bug_id > 0}
  File "/workspace/dashboard/alerts.py", line 268, in <setcomp>
    bug_id_list = {a.bug_id for a in anomalies if a.bug_id > 0}
TypeError: '>' not supported between instances of 'NoneType' and 'int'

Bug: chromium:1298177
Change-Id: Ied37aed9df194c44b4e6321612108d54392d19b2