Create patch set 7
Change has been successfully rebased and submitted as 747caedcf238032a500f8286bfe9ad3074a1b16d

4 is the latest approved patch-set.
The change was submitted with unreviewed changes in the following files:

```
The name of the file: dashboard/dashboard/pinpoint/models/change/patch.py
Insertions: 3, Deletions: 3.

@@ -10,7 +10,7 @@
 import datetime
 import logging
 import re
-import six.moves.urllib.parse
+import six.moves.urllib.parse as urlparse
 
 from dashboard.pinpoint.models import errors
 from dashboard.pinpoint.models.change import commit_cache
@@ -149,8 +149,8 @@
       KeyError: The patch doesn't have the given revision.
       ValueError: The URL has an unrecognized format.
     """
-    url_parts = six.moves.urllib.parse.urlparse(url)
-    server = six.moves.urllib.parse.urlunsplit(
+    url_parts = urlparse.urlparse(url)
+    server = urlparse.urlunsplit(
         (url_parts.scheme, url_parts.netloc, '', '', ''))
 
     change_rev_match = re.match(r'^https.*\/\+\/(\d+)(?:\/(\d+))?\/?$', url)
```


Patch-set: 7
Patch-set-description: Rebase
Subject: [Pinpoint] Python 3 migration - import_six and dict_six
Status: merged
Commit: 747caedcf238032a500f8286bfe9ad3074a1b16d
Tag: autogenerated:gerrit:merged
Groups: 5002a1bd36bcd4c1671616ef7f746d40cc0bf8d8
Label: Auto-Submit=+1, ba492949cb21dfcbf370fd0228b69455d5d0ce25 Gerrit User 1521022 <1521022@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Code-Review=+1, 1d51256749b76099228f087694bbc86bf96f5fd6 Gerrit User 1373330 <1373330@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=+2, c7bad72456e114a91a60628085358cd693c41843 Gerrit User 1521022 <1521022@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: SUBM=+1, be7a48bf8b444b1b2923a3907312f30a63038eb2
Submission-id: 3584492
Submitted-with: OK
Submitted-with: Rule-Name: gerrit~DefaultSubmitRule
Submitted-with: MAY: Auto-Submit: Gerrit User 1521022 <1521022@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Submitted-with: MAY: Code-Review: Gerrit User 1373330 <1373330@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Submitted-with: MAY: Commit-Queue: Gerrit User 1521022 <1521022@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Submitted-with: MAY: Bot-Commit
Submitted-with: MAY: Owners-Override
Submitted-with: OK
Submitted-with: Rule-Name: Code-Owners