Fix TypeError in Anomaly.QueryAsync.
TypeError: %d format: a number is required, not datetime.datetime
Change-Id: Ibbebe3fe0a39878563dcf794af71ba5b3a3a46e5