Reland "[Telemetry] Refactor expectations code into story_filter.py."
This relands https://chromium-review.googlesource.com/c/catapult/+/1839176
It was reverted by https://chromium-review.googlesource.com/c/catapult/+/1864789
Because it broke system_health_smoke_tests with the error
  Traceback (most recent call last):
    RunBenchmark at /b/swarming/w/ir/third_party/catapult/telemetry/telemetry/internal/story_runner.py:439
      max_num_values=benchmark.MAX_NUM_VALUES)
    RunStorySet at /b/swarming/w/ir/third_party/catapult/telemetry/telemetry/internal/story_runner.py:234
      results.benchmark_name, platform_tags)
    BuildStoryFilter at /b/swarming/w/ir/third_party/catapult/telemetry/telemetry/story/story_filter.py:58
      cls._expectations.GetBenchmarkExpectationsFromParser(fh.read())
  AttributeError: type object 'StoryFilterFactory' has no attribute '_expectations'

Change-Id: I5f3ce1b07569652b734bd1051667fbed0baabb3d