[chromeperf] further fixes on the byte conversion on upload-processing
The previous fix did not fully fix the issue: https://chromium-review.googlesource.com/c/catapult/+/4070864. The following error happened:

File "/layers/google.python.pip/pip/lib/python3.9/site-packages/ijson/compat.py", line 32, in read
    return self.str_reader.read(n).encode('utf-8')
AttributeError: 'bytes' object has no attribute 'encode'

The suspected culprit is the DecompressFileWrapper which returns unicode string (I don't know why) when the buffer to read is empty. That will confuse ijson that the data is string instead of byte, and thus ijson will further encode it.

More context:
- ijson has a compat module to handler py2/py3 compatibility. In the latest version (added in requirements.txt), it reads 0 bytes from the file to tell whether it is byte type.
https://github.com/ICRAR/ijson/blob/master/ijson/compat.py
- In the decompress wrapper, it reads the gcs file and decompresses the content. While decompress normally returns bytes, read(0) returns u’’, which confuses ijson that the data is string type. Thus, a utf8reader is used to encode future reads, even when the future reads return decompressed bytes.
https://source.chromium.org/chromium/chromium/src/+/main:third_party/catapult/dashboard/dashboard/add_histograms.py;l=657


Bug: chromium:1298177
Change-Id: I6d7c8c5c985e944343ce20471a69123f1c44cda7