Reland "Do not use iteritems"
This reverts commit 7c0bc6acf8793293e5ac3a5e4c6693af4dc8b51a.

Reason for revert: This revert will not fix the issue, since it breaks catapult auto roll (crbug/1192704). Reland this, and provide a different fix through 1191444

Original change's description:
> Revert "Do not use iteritems"
>
> This reverts commit 7a3a7363a7c321684eb327d1b8aa536986a12ff8.
>
> Reason for revert: The usage of the package six has caused failures on bot https://ci.chromium.org/p/chrome/builders/ci/orderfile-clankium since 2020-03-10 for missing six:
>
> File "/b/swarming/w/ir/cache/builder/src/third_party/catapult/devil/devil/devil_env.py", line 20, in <module>
>     import six
> ImportError: No module named six
>
> TBR=jbudorick@chromium.org
>
> Original change's description:
> > Do not use iteritems
> >
> > Use six.iteritems() instead
> > Also fix a type error when write str to tmpfile in py3,
> > as default mode will be 'wb'
> >
> > Bug: chromium:1185409
> > Change-Id: I5c98611623fc4177d4c88c42924b6eacc9d36f44
> > Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/2739660
> > Reviewed-by: Ben Pastene <bpastene@chromium.org>
> > Reviewed-by: Nate Fischer <ntfschr@chromium.org>
> > Reviewed-by: Dirk Pranke <dpranke@google.com>
> > Commit-Queue: Weizhong Xia <weizhong@google.com>
>
> Bug: chromium:1185409
> Change-Id: Ib33b28bc8a204d09a9646f3714da752982b937a3
> Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/2786740
> Reviewed-by: Alice Wang <aliceywang@chromium.org>
> Commit-Queue: Alice Wang <aliceywang@chromium.org>

Bug: chromium:1185409
Change-Id: Idaaa9925dd39ccc0667147e61e059473e427c137