[Fuchsia] Add --output-error=warn for tee to avoid breaking pipe
It causes issues like

  print_ at /b/s/w/ir/third_party/catapult/third_party/typ/typ/runner.py:196
    self.host.print_(msg, end, stream=stream)
  print_ at /b/s/w/ir/third_party/catapult/third_party/typ/typ/host.py:160
    stream.flush()
BlockingIOError: [Errno 11] write could not complete without blocking

Due to tee: 'standard output': Resource temporarily unavailable

Change-Id: Id02dd3692d3a978d6fa5106bebc41f11693f2545