Revert "Rename add_reserved_diagnostics to prepare_upload, keep alias."
This reverts commit 6d35d61a1776b8adf9c4cc0c485399d4b509ccab.

Reason for revert: blocking roll
  File "/b/swarming/w/ir/third_party/catapult/tracing/bin/add_reserved_diagnostics", line 11, in <module>
    exec(open(os.path.join(os.path.dirname(__file__), 'prepare_upload')).read())
  File "<string>", line 113, in <module>
  File "<string>", line 103, in main
TypeError: expected a string or other character buffer object
https://chromium-swarm.appspot.com/task?id=4301aad824e1d310

Original change's description:
> Rename add_reserved_diagnostics to prepare_upload, keep alias.
> 
> tracing/bin/add_reserved_diagnostics originally only added metadata diagnostics,
> but has since accrued other functionality required to prepare HistogramSets for
> upload to the chromeperf dashboard.
> 
> This CL renames the script to `prepare_upload`, and retains
> `add_reserved_diagnostics` as an alias for the new script until callers can
> migrate to the new name.
> A followup CL will split the tracing.value.diagnostics.add_reserved_diagnostics
> module into appropriately-named modules.
> 
> Change-Id: If872d873464a1fbcc5005328c25662529e935f1b
> Reviewed-on: https://chromium-review.googlesource.com/c/1449636
> Commit-Queue: Ben Hayden <benjhayden@chromium.org>
> Reviewed-by: Simon Hatch <simonhatch@chromium.org>
> Reviewed-by: Caleb Rouleau <crouleau@chromium.org>

TBR=benjhayden@chromium.org,simonhatch@chromium.org,crouleau@chromium.org

Change-Id: I887d5362a44a1a156d7733aee7d44036a313511e
No-Presubmit: true
No-Tree-Checks: true
No-Try: true