Revert "[Pinpoint] prevent auto bisection from bisecting improvements"
This reverts commit 338b5a870f426b3a5b0b431ba6f1061c7ff562f8.

Reason for revert: This is causing AttributeError: 'JobState' object has no attribute '_improvement_direction' in:

File "/workspace/dashboard/pinpoint/models/job_state.py", line 394, in _Compare: 
  or mean_diff < 0 and self._improvement_direction == anomaly.DOWN):

Original change's description:
> [Pinpoint] prevent auto bisection from bisecting improvements
>
> This CL only works on auto-bisection because manual bisections do not populate the "tags" input parameter, which is used to fetch the improvement direction from TestMetadata in DataStore.
>
> Bug: chromium:1351167
> Change-Id: Id5546c31ac81b9a043396db817f6218607c5e16f
> Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/4795192
> Reviewed-by: John Chen <johnchen@chromium.org>
> Commit-Queue: Leina Sun <sunxiaodi@google.com>
> Reviewed-by: Wenbin Zhang <wenbinzhang@google.com>

Bug: chromium:1351167
Change-Id: Ide6e74a716bbaa91126d57ffec6c6cce9c33e862
No-Presubmit: true
No-Tree-Checks: true
No-Try: true