[chromeperf] remove unnecessary index
This index prevents `gcloud datastore indexes create index.yaml` from succeeding.

```
ERROR: (gcloud.datastore.indexes.create) INVALID_ARGUMENT: This index:
Datastore index on 'Job' for (created DESC)
is not necessary, since single-property indexes are built in. Please remove it from your index file and upgrade to the latest version of the SDK, if you haven't already.
- '@type': type.googleapis.com/google.rpc.DebugInfo
  detail: |-
    This index:
    Datastore index on 'Job' for (created DESC)
    is not necessary, since single-property indexes are built in. Please remove it from your index file and upgrade to the latest version of the SDK, if you haven't already.
```

Bug: chromium:1377146
Change-Id: I77b5a076ba7d774aee3f057a1bfd96741fcfb5ed