Revert "Fix encoding bug in typ"
This reverts commit 4f0d7594338dae0097f3b45b88876d61613bff63.

Reason for revert: The cloud build for chromeperf is failing due to this change:

Traceback (most recent call last):
  File "/workspace/third_party/typ/typ/runner.py", line 1385, in <module>
    sys.exit(main(win_multiprocessing=WinMultiprocessing.importable))
  File "/workspace/third_party/typ/typ/runner.py", line 73, in main
    return runner.main(argv, **defaults)
  File "/workspace/third_party/typ/typ/runner.py", line 178, in main
    ret, _, _ = self.run()
  File "/workspace/third_party/typ/typ/runner.py", line 258, in run
    self.print_('Start running tests: %s' % str(datetime.now()))
  File "/workspace/third_party/typ/typ/runner.py", line 196, in print_
    self.host.print_(msg, end, stream=stream)
  File "/workspace/third_party/typ/typ/host.py", line 155, in print_
    errors='backslashreplace').decode(stream.encoding))
TypeError: encode() argument 1 must be string, not None



Original change's description:
> Fix encoding bug in typ
>
> On Windows method |typ.host.Host.print_| can fail on non-ASCII symbols.
> For example, cp1252 does not contain cyrillic symbols and |print_| will
> fail.
> In this CL we replace "bad" symbols from message to backslash sequence
> before output.
>
> Change-Id: Ibc03c4320aa665e2e40108c99b11e21cbb8a10b7
> Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/4048250
> Auto-Submit: Victor Samun <victorsamun@yandex-team.ru>
> Commit-Queue: Dirk Pranke <dpranke@google.com>
> Reviewed-by: Dirk Pranke <dpranke@google.com>

Change-Id: I413398bf31dedfdfa887c19f05b1f3c2de26d646
No-Presubmit: true
No-Tree-Checks: true
No-Try: true