Update patch set 9
Patch Set 9: Commit-Queue+1

(1 comment)

> Patch Set 6:
> 
> Looks good overall, though I'm not a fan with having a `FromProto` to every diagnostic type -- but I guess that's what we need to do anyway?

Yeah, that could be refactored. There's a fromdicts on each now, so I tried to be consistent with that. I do like that each class knows best how to deserialize itself. This will look better if we get rid of dicts and/or the serialized format so there's not three deserialization methods on each class.

We could probably rewrite diagnostics to not rely on setattr/getattr and importlib madness. This is prohibited in google style for good reason. I could imagine something like this in diagnostic.py:

t = dct['type']
if t == 'Breakdown':
  result = breakdown.Breakdown.FromDict(dct)
elif t == 'GenericSet':
  result = ...
...
else:
  raise ValueError('Unrecognized...')

if 'guid' in dct:
  result.guid = dct['guid']

return result

Essentially, we get rid of all_diagnostics.py and just write everything out straight. The python interpreter will have to load a bit more modules on startup, but that's a highly dubious optimization anyway. For now I will use the prevailing style which is getattr/setattr black magic.

> 
> BTW, the error is at:
> 
> ```
> Failed to import test module: add_histograms_queue_test
> Traceback (most recent call last):
>   File "/b/s/w/ir/cipd_bin_packages/cpython/lib/python2.7/unittest/loader.py", line 254, in _find_tests
>     module = self._get_module_from_name(name)
>   File "/b/s/w/ir/cipd_bin_packages/cpython/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
>     __import__(name)
>   File "/b/s/w/ir/k/catapult/dashboard/dashboard/add_histograms_queue_test.py", line 17, in <module>
>     from dashboard import add_histograms_queue
>   File "/b/s/w/ir/k/catapult/dashboard/dashboard/add_histograms_queue.py", line 28, in <module>
>     from tracing.value import histogram as histogram_module
>   File "/b/s/w/ir/k/catapult/tracing/tracing/value/histogram.py", line 21, in <module>
>     from tracing import histogram_pb2
> ImportError: cannot import name histogram_pb2
> ```
> 
> You probably need to ensure that the histogram proto is built in the Dashboard tests from  `catapult_build/build_steps.py`.
> 
> https://source.chromium.org/chromium/_/chromium/catapult.git/+/09b742896513eb94aa3cd506f7c4bc5dcce84f95:catapult_build/build_steps.py;l=247-271;drc=13cb57d5162ade2775ae1bcf8ba0f06cf6f31332?originalUrl=https:%2F%2Fcs.chromium.org%2F

Patch-set: 9
Reviewer: Gerrit User 1002301 <1002301@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=+1