Revert "update chromeperf deployment for perf-issue-service"
This reverts commit ef7eb2c032107594ca0c60751f5cea978bbf0644.

Reason for revert: Found issue in alertgroup:
File "/home/vmagent/app/models/alert_group.py", line 163, in GetGroupsForAnomaly
    g['project_id'] == s.get('monorail_project_id', '') and
KeyError: 'project_id'

Original change's description:
> update chromeperf deployment for perf-issue-service
>
> https://chromium.googlesource.com/catapult.git/+log/a55f4cc..e8ae187
>
> Bug: chromium:1475124
> Change-Id: I34d35999bbd8f1fd58db555eac2a3d1a8d0e8bf3
> Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/4804749
> Commit-Queue: Sean McCullough <seanmccullough@google.com>
> Auto-Submit: Hao Wu <haowoo@google.com>
> Commit-Queue: Hao Wu <haowoo@google.com>
> Reviewed-by: Sean McCullough <seanmccullough@google.com>
> Reviewed-by: Wenbin Zhang <wenbinzhang@google.com>

Bug: chromium:1475124
Change-Id: If6f7aa994cbf364126a2ad34286f0c0b3c782268
No-Presubmit: true
No-Tree-Checks: true
No-Try: true