Update patch set 1
Patch Set 1:

Had never been so happy about seeing a red tryjob!

We were lucky and without landing it was able to single out the culprit:

[1/1] telemetry.internal.app.android_app_unittest.AndroidAppTest.testWebView failed unexpectedly 3.5299s:
  Traceback (most recent call last):
    File "/b/swarming/w/ir/k/catapult/telemetry/telemetry/internal/app/android_app_unittest.py", line 46, in testWebView
      search_process._UpdateDevToolsClient()
    File "/b/swarming/w/ir/k/catapult/telemetry/telemetry/internal/app/android_process.py", line 43, in _UpdateDevToolsClient
      app_backend=self._app_backend)
    File "/b/swarming/w/ir/k/catapult/telemetry/telemetry/internal/backends/chrome_inspector/devtools_client_backend.py", line 54, in GetDevToolsBackEndIfReady
      client.Connect(devtools_port, browser_target)
    File "/b/swarming/w/ir/k/catapult/telemetry/telemetry/internal/backends/chrome_inspector/devtools_client_backend.py", line 157, in Connect
      self._Connect(devtools_port, browser_target)
    File "/b/swarming/w/ir/k/catapult/telemetry/telemetry/internal/backends/chrome_inspector/devtools_client_backend.py", line 188, in _Connect
      'Chrome branch number %d is no longer supported' % branch_number)
  UnsupportedVersionError: Chrome branch number 2403 is no longer supported

That "AndroidApp" was another attempt at making Telemetry more general and able to connect to other (non-Chrome) apps on Android. But it's not really used at the moment so I'll start chopping off that feature.

Patch-set: 1
Reviewer: Gerrit User 1123010 <1123010@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=0