Update patch set 5
Patch Set 5:

This appears to be blocking roll by breaking chromedriver_py_tests on linux.
https://chromium-review.googlesource.com/c/chromium/src/+/1432776
https://ci.chromium.org/p/chromium/builders/luci.chromium.try/linux_chromium_rel_ng/280263
https://chromium-swarm.appspot.com/task?id=429672e842030e10&refresh=10&show_raw=1
Traceback (most recent call last):
  File "../../chrome/test/chromedriver/test/run_py_tests.py", line 64, in <module>
    from devil.android import device_utils
  File "/b/s/w/ir/third_party/catapult/devil/devil/android/device_utils.py", line 33, in <module>
    from devil.android import apk_helper
  File "/b/s/w/ir/third_party/catapult/devil/devil/android/apk_helper.py", line 11, in <module>
    from devil.android.ndk import abis
ImportError: No module named ndk

I see the __init__.py in this CL, so I'm not sure what could cause the ImportError.

Patch-set: 5
CC: Gerrit User 1115874 <1115874@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>