Update patch set 1
Patch Set 1:

(1 comment)

> Patch Set 1:
> 
> Based on the docstring of FindBrowser():
>   Returns:
>     A PossibleBrowser object.
>   Raises:
>     BrowserFinderException: Options improperly set, or an error occurred.
> 
> Caller should receive a PossibleBrowser object or exception. But if there're more than a few caller handling None instead of catching exception, then we should at least fix the docstring.
> 
> Though I prefer treating "cannot find any browser" as an exception because it is definitely something wrong for the platform.

Yeah, I see there are at least a handful of callers which are happy to receive a "None" browser and finish early or skip some test (without causing an error).

I would vote to just fix the docstring to make the current behavior explicit.

Alternatively, if you want to go for the API change (raise rather than return None), then we would need to make sure all of the clients [1] are updated to match this new expectation (e.g. remove extra error raising in case browser is none; and try-catch-dismiss the exception when that was the intended behavior).

[1]: https://cs.chromium.org/search/?q=%5C.FindBrowser%5C(+-file:%5Esrc/third_party/android_tools+-file:%5Einfra/infra/services/android_docker&type=cs

Patch-set: 1
Reviewer: Gerrit User 1123010 <1123010@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>