Update patch set 6
Patch Set 6:

> Patch Set 6:
> 
> Did some testing in dev_console with queries that have no composite index, like querying on description/overridden_anomaly_config and seems to work fine. Had some slight concerns there might be some weirdness surrounding the computed properties, but poking through the source reveals that they're indexed by default although there isn't much mention in the docs.
> 
> Any idea if the non-composite index backed query performs similarly? This will definitely impact people since list_tests is used by the test-picker.

I changed the CL to keep the index for the deprecated,description projection query because it seems to make all the difference in performance for update_test_suites.

I believe list_tests is already using the builtin indexes instead of the composite indexes. The composite indexes would only support queries that specify all of master_name,bot_name,suite_name,test_part1_name,test_part2_name,test_part3_name,test_part4_name,test_part5_name. If a query specifies all parts of the test path, uniquely identifying a single TestMetadata entity, then why run the query in the first place?

> 
> This isn't super high priority though, so maybe let's try this once all the alerts indexes stuff has landed. Also for the Test entity, should we also be removing these from datastore? Anybody know?

The Test Model has been removed, so you can't even get a Test entity by key.
from google.appengine.ext import ndb
print ndb.Key('Master', 'ChromeOSPerf', 'Bot', 'cros-butterfly', 'Test', 'build_RootFilesystemSize', 'Test', 'bytes_rootfs_prod').get()
KindError: No model class found for kind 'Test'. Did you forget to import it?

Row still uses Test Keys for its parent_test computed property, which is used to define all its composite indexes. However, it doesn't appear to be necessary for the Test entities to exist for these Test Keys. I created a Row entity whose parent is ndb.Key('TestMetadata','ChromeOSPerfFyi/histogram-diff-chartjson-13/system_health.common_desktop/benchmark_duration/foo'). I can find it in the datastore by filtering for parent_test=Key(Master, 'ChromeOSPerfFyi', Bot, 'histogram-diff-chartjson-13', Test, 'system_health.common_desktop', Test, 'benchmark_duration', Test, 'foo') even though no such Test entity exists.

It looks to me like it would be safe to delete all of the Test entities.

Patch-set: 6