Update patch set 6
Patch Set 6:

Now we're failing because we don't have `flask` available in the builders:

```
Failed to import test module: sheriff_config.tests.sheriff_config_test
Traceback (most recent call last):
  File "/b/s/w/ir/cipd_bin_packages/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/b/s/w/ir/cipd_bin_packages/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/b/s/w/ir/k/catapult/dashboard/dashboard/sheriff_config/tests/sheriff_config_test.py", line 15, in <module>
    from dashboard.sheriff_config import service
  File "/b/s/w/ir/k/catapult/dashboard/dashboard/sheriff_config/service/__init__.py", line 12, in <module>
    from flask import Flask, request, jsonify
ImportError: No module named flask
```

Filed request for vpython wheel to make it available: https://crbug.com/959087

Is there something special we need to do in the build configuration to get the vpython package dependencies installed in the builders?

Patch-set: 6
Reviewer: Gerrit User 1327821 <1327821@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=0