Update patch set 1
Patch Set 1:

Note that since we only include the last line of the stack trace, the result will look like:
> All of the runs failed. The most common error (9/10 runs) was:
> AttributeError: 'Namespace' object has no attribute 'benchmark_names'


Instead of:
> All of the runs failed. The most common error (9/10 runs) was:
> SwarmingTestError: The test failed. The test's error message was:
> AttributeError: 'Namespace' object has no attribute 'benchmark_names'

Patch-set: 1
Reviewer: Gerrit User 1001913 <1001913@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Reviewer: Gerrit User 1123010 <1123010@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Reviewer: Gerrit User 1000093 <1000093@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Work-in-progress: false