[skia-bridge] Fix the startup error.
- Currently the skia bridge app is failing to start with the error below.
- Turns out this is due to an update in Werkzeug package (dependency of Flask) which has a breaking change. Assigning a specific version of this package.

Step #0:   File "/workspace/application/app.py", line 6, in <module>
Step #0:     from flask import Flask
Step #0:   File "/layers/google.python.pip/pip/lib/python3.11/site-packages/flask/__init__.py", line 5, in <module>
Step #0:     from .app import Flask as Flask
Step #0:   File "/layers/google.python.pip/pip/lib/python3.11/site-packages/flask/app.py", line 30, in <module>
Step #0:     from werkzeug.urls import url_quote
Step #0: ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/layers/google.python.pip/pip/lib/python3.11/site-packages/werkzeug/urls.py)

Change-Id: Ia12b78b60bcb71c5fff4e16bc96cd8d7d61b8dde