Revert "Add .vpython file for histogram_proto.py."
This reverts commit cb4bb2088ad7d6b27fb0ea180ce59cf810e5f520.

Reason for revert: It doesn't fix the issue, see https://bugs.chromium.org/p/webrtc/issues/detail?id=12211#c8 for an
explanation.

Original change's description:
> Add .vpython file for histogram_proto.py.
>
> Starting from [1], //third_party/protobuf has been updated to 3.13.0
> and this introduces a breaking change which breaks WebRTC's perf results
> upload (see bugs.webrtc.org/12211).
>
> Error:
>
> File [..]/tracing/proto/histogram_proto.py", line 9, in <module>
>     import histogram_pb2  # pylint:disable=relative-import
>   File "[..]/tracing/proto/histogram_pb2.py", line 22, in <module>
>     create_key=_descriptor._internal_create_key,
> AttributeError: 'module' object has no attribute '_internal_create_key'
>
> [1] - https://chromium-review.googlesource.com/c/chromium/src/+/2545204
>
> (See bugs.webrtc.org/12211)
>
> Bug: None
>
> Change-Id: I43d624fe29948c72421a5da55f4ffcd8e2dac942
> Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/2553541
> Commit-Queue: Mirko Bonadei <mbonadei@chromium.org>
> Reviewed-by: Dean Berris <dberris@chromium.org>

TBR=bpastene@chromium.org,mbonadei@chromium.org,dberris@chromium.org

Change-Id: I04717ee72f4f109b0346edd39aeeb2fd6ff5ab41
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: None