Update patch set 5
Patch Set 5:

> Patch Set 5:
> 
> > Patch Set 5:
> > 
> > This appears to be blocking roll by breaking chromedriver_py_tests on linux.
> > https://chromium-review.googlesource.com/c/chromium/src/+/1432776
> > https://ci.chromium.org/p/chromium/builders/luci.chromium.try/linux_chromium_rel_ng/280263
> > https://chromium-swarm.appspot.com/task?id=429672e842030e10&refresh=10&show_raw=1
> > Traceback (most recent call last):
> >   File "../../chrome/test/chromedriver/test/run_py_tests.py", line 64, in <module>
> >     from devil.android import device_utils
> >   File "/b/s/w/ir/third_party/catapult/devil/devil/android/device_utils.py", line 33, in <module>
> >     from devil.android import apk_helper
> >   File "/b/s/w/ir/third_party/catapult/devil/devil/android/apk_helper.py", line 11, in <module>
> >     from devil.android.ndk import abis
> > ImportError: No module named ndk
> > 
> > I see the __init__.py in this CL, so I'm not sure what could cause the ImportError.
> 
> Huh. Not sure why that's happening. Adding __init__.py fixed that error when I ran the presubmit tests. jbudorick@ or perezju@ might know?
> 
> I can run "python chrome/test/chromedriver/test/run_py_tests.py" without hitting the import error.
> 
> This is safe to revert, although I don't see the bug on my end (so I'm not sure how to fix it, if that's the case)

The new files probably aren't in the isolate; they'll need to be added to https://codesearch.chromium.org/chromium/src/chrome/test/chromedriver/test/run_py_tests.pydeps. I would guess that there may be other pydeps files to which these also need to be added. The best way to proceed is likely to stop the catapult autoroller and perform a manual roll that updates the pydeps files in the same CL.

Patch-set: 5