[Sheriff] Add log info to testSystemInfoModelNameOnMac
Test has been failing on bots, but it's not clear why it's failing
and what CL caused the failure. The failure happens in the line where
it check if the info_model satisfies the re pattern, but there is no
info about what is being matched against in logs. Adding some logging
to help us identify what's up here.

These are the logs as they show up today:

Traceback (most recent call last):
  File "/opt/s/w/ir/third_party/catapult/telemetry/telemetry/testing/browser_test_case.py", line 39, in WrappedMethod
    method(self)
  File "/opt/s/w/ir/third_party/catapult/telemetry/telemetry/internal/browser/browser_unittest.py", line 150, in testSystemInfoModelNameOnMac
    self.assertNotEqual(re.match(model_name_re, info.model_name), None)
AssertionError: None == None


Bug: chromium:1286736
Change-Id: I736e4116ad22c62c0d98f04b2360a3ee499f93a7