Revert "Add more information to log to evaluate the impact of the threshold"
This reverts commit b70c5247606781c2fdf709912fa00bb4d8f063ca.

Reason for revert: We are getting "AttributeError
'JobState' object has no attribute '_benchmark_arguments'" on Pinpoint

Original change's description:
> Add more information to log to evaluate the impact of the threshold
> update.
>
> Change-Id: I34554d364ce8ec9f0b50aea035b5cfd5ff2c5e80
> Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/5311519
> Reviewed-by: Ashwin Verleker <ashwinpv@google.com>
> Commit-Queue: Alex Sun <sunpeng@google.com>
> Reviewed-by: Leina Sun <sunxiaodi@google.com>

Change-Id: I3b3ce099a2d7ba871ce2e4249eae6e293d5ca6d6
No-Presubmit: true
No-Tree-Checks: true
No-Try: true