Update patch set 2
Patch Set 2:

> Patch Set 2: Code-Review+1
> 
> Exciting to see this change!
> 
> Is there anything you can do to prevent regressions? For example, does adding --py3k to our pylint checks work? (https://portingguide.readthedocs.io/en/latest/tools.html#automated-checker-pylint-py3k)

That's a good idea, and it's certainly worth a try!

Let me update with that change to prevent regressions.

I think I'm also running into dict order instability with one of the tests in pinpoint already, like so:

```
[1057/1336] pinpoint.models.job_test.BugCommentTest.testCompletedWithCommitAndDocs failed unexpectedly:
    Traceback (most recent call last):
      File "C:\b\s\w\ir\k\catapult\third_party\mock\mock.py", line 1201, in patched
        return func(*args, **keywargs)
      File "C:\b\s\w\ir\k\catapult\dashboard\dashboard\pinpoint\models\job_test.py", line 380, in testCompletedWithCommitAndDocs
        cc_list=['author@chromium.org'], merge_issue=None)
      File "C:\b\s\w\ir\k\catapult\third_party\mock\mock.py", line 846, in assert_called_once_with
        return self.assert_called_with(*args, **kwargs)
      File "C:\b\s\w\ir\k\catapult\third_party\mock\mock.py", line 835, in assert_called_with
        raise AssertionError(msg)
    AssertionError: Expected call: AddBugComment(123456, u'<b>\U0001f4cd Found a significant difference after 1 commit.</b>\nhttps://testbed.example.com/job/1\n\n<b>Subject.</b> by author@chromium.org\nhttps://example.com/repository/+/git_hash\n0 \u2192 1.235 (+1.235)\n\nUnderstanding performance regressions:\n  http://g.co/ChromePerformanceRegressions\n\nBenchmark doc link:\n  http://docs', status='Assigned', owner='author@chromium.org', cc_list=['author@chromium.org'], merge_issue=None)
    Actual call: AddBugComment(123456, u'<b>\U0001f4cd Found a significant difference after 1 commit.</b>\nhttps://testbed.example.com/job/1\n\n<b>Subject.</b> by author@chromium.org\nhttps://example.com/repository/+/git_hash\n0 \u2192 1.235 (+1.235)\n\nUnderstanding performance regressions:\n  http://g.co/ChromePerformanceRegressions', owner='author@chromium.org', status='Assigned', cc_list=['author@chromium.org'], merge_issue=None)
```

Seems the difference is in the ordering between `status` and `owner` for keyword arguments.

https://cs.chromium.org/chromium/src/third_party/catapult/dashboard/dashboard/pinpoint/models/job_test.py?l=377&rcl=178118d233d98876cdf0cb472e7c91614cc1988f

(From https://logs.chromium.org/logs/catapult/buildbucket/cr-buildbucket.appspot.com/8914652052461851152/+/steps/Dashboard_Python_Tests/0/stdout)

Patch-set: 2
Reviewer: Gerrit User 1327821 <1327821@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>