Update patch set 16
Patch Set 16:

> Patch Set 16:
> 
> > Patch Set 15:
> > 
> > Ah, somehow I missed that existing file also does have the >> mark. lgtm then. Sorry for unnecessary style nit.
> > 
> > Before you land, can you run "./telemetry/bin/update_wpr_go_binary" and submit the CL again?
> 
> I keep getting an error when running the update_wpr_go_binary script:
> 
> CalledProcessError: Command '['go', 'build', '-v', 'wpr.go']' returned non-zero exit status 2
> 
> However, the 'go build -v wpr.go' command finishes without error if I run it myself manually.

I think you may need to tinker with https://cs.chromium.org/chromium/src/third_party/catapult/telemetry/bin/update_wpr_go_binary?rcl=3cf15a9b47a0f81ff31921349a845275dc92f5b4&l=25 a bit

Patch-set: 16
Reviewer: Gerrit User 1128435 <1128435@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>