[Memory Infra] symbolize_trace.py bugfix
When running symbolize_trace.py on a trace with memory infra heap dumps
I ran into the following error:

File
"third_party/catapult/tracing/tracing/extras/symbolizer/symbolize_trace.py",
line 394, in __init__
    region._code_id = '%08X%X' % (int(region_node['ts'], 16), region.size)
TypeError: int() can't convert non-string with explicit base

I think the region_node['ts'] needs to be cast to a str(). This might be
a python3 issue?

Bug: chromium:1268897
Change-Id: Ib24cf48630439157e081c0bd06156728fca67451