Create patch set 3
Change has been successfully rebased and submitted as dc3e9bf012e68f78efc07dff48cdc023fc130739

1 is the latest approved patch-set.
The change was submitted with unreviewed changes in the following files:

```
The name of the file: devil/devil/android/sdk/adb_wrapper.py
Insertions: 2, Deletions: 2.

@@ -646,8 +646,8 @@
       timeout: Timeout in seconds.
       retries: Number of retries.
       check_error: Check that the command doesn't return an error message. This
-        does check the error status of adb but DOES NOT check the exit status
-        of shell commands.
+        checks both the error status of adb and the exit status of shell
+        commands.
 
     Returns:
       The output of the command.
```


Patch-set: 3
Patch-set-description: Rebase
Subject: Devil: suppress errors in Logcat
Status: merged
Commit: dc3e9bf012e68f78efc07dff48cdc023fc130739
Tag: autogenerated:gerrit:merged
Groups: 8d41408e3d4e204f0236817bf447a2e0e2b676b0
Label: Code-Review=+1, 9d8ffb08a2189d7beb38399471033a09ebe25d36 Gerrit User 1170419 <1170419@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=+2, 0c457bf7cecc3eefeab283af45c3b50706091cd6 Gerrit User 1167294 <1167294@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: SUBM=+1, 5bddd1570004d3db54f795c2f7c0344ba6680b11
Submission-id: 3975878
Submitted-with: OK
Submitted-with: Rule-Name: gerrit~DefaultSubmitRule
Submitted-with: MAY: Auto-Submit
Submitted-with: MAY: Code-Review: Gerrit User 1170419 <1170419@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Submitted-with: MAY: Commit-Queue: Gerrit User 1167294 <1167294@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Submitted-with: MAY: Bot-Commit
Submitted-with: MAY: Owners-Override
Submitted-with: OK
Submitted-with: Rule-Name: Code-Owners