Update patch set 7
Patch Set 7:

Looks like your test fix doesn't work when an actual DeviceUtils instance is used:

Traceback (most recent call last):
    File "/b/swarming/w/ir/k/catapult/telemetry/telemetry/testing/browser_test_case.py", line 38, in WrappedMethod
      method(self)
    File "/b/swarming/w/ir/k/catapult/telemetry/telemetry/internal/actions/action_runner_unittest.py", line 59, in testDeterministicMode
      self._TestWithTracing(deterministic_mode=True)
    File "/b/swarming/w/ir/k/catapult/telemetry/telemetry/internal/actions/action_runner_unittest.py", line 41, in _TestWithTracing
      self._browser.platform.tracing_controller.StartTracing(config)
    File "/b/swarming/w/ir/k/catapult/telemetry/telemetry/core/tracing_controller.py", line 34, in StartTracing
      self._tracing_controller_backend.StartTracing(tracing_config, timeout)
    File "/b/swarming/w/ir/k/catapult/telemetry/telemetry/internal/platform/tracing_controller_backend.py", line 123, in StartTracing
      agent = agent_class(self._platform_backend)
    File "/b/swarming/w/ir/k/catapult/telemetry/telemetry/internal/platform/tracing_agent/atrace_tracing_agent.py", line 20, in __init__
      platform_backend.device.tracing_path)
  AttributeError: 'DeviceUtils' object has no attribute 'tracing_path'

Patch-set: 7
Label: Commit-Queue=0